# Algebra de tensores

Este taller busca presentar el concepto de tensores, sus tipo, formas y dimensión asi como su manipulación:

![LRUrl](https://www.tensorflow.org/site-assets/images/marketing/partners/aisp_step1.svg)

1. Importar paquetes o librerias
2. Definición de tensor, ejemplos y visualización de su forma (shape)
3. Definición técnica de tensores y visualización forma y tipo
4. Operaciones algebraicas con tensores
5. Pasar un tensor a un arreglo, ubicar una posición ó una rebanada específica
6. Manipulación de su forma (shape)
7. Aplanar un tensor
8. Transmitir (Broadcasting)
9. Tensores tipo irregulares (ragged)
10. Tensor tipo cadena (string)
11. Tensores tipo dispersos (sparse)

#### Paso 1. Importar paquetes o librerias

In [26]:
import tensorflow as tf
import numpy as np

#### Paso 2. Definición de tensor, ejemplos y visualización de su forma (shape)

Los tensores son arreglos multidimensionales, en los que podemos trabajar con número scalares, vectores, matrices o arreglos de matrices, ubicados en diferentes composiciones. Las imágenes a continuación muestran alguno ejemplos:

![LRUrl](https://www.tensorflow.org/guide/images/tensor/scalar.png)
![LRUrl](https://www.tensorflow.org/guide/images/tensor/vector.png)
![LRUrl](https://www.tensorflow.org/guide/images/tensor/matrix.png)
![LRUrl](https://www.tensorflow.org/guide/images/tensor/3-axis_numpy.png)
![LRUrl](https://www.tensorflow.org/guide/images/tensor/3-axis_front.png)
![LRUrl](https://www.tensorflow.org/guide/images/tensor/3-axis_block.png)

#### Paso 3. Definición técnica de tensores y visualización forma y tipo

In [27]:
# Escalar=tensor de orden 0
t0 = tf.constant(4)
print("Escalar:\n", t0, "\n")

#Vector = tensor de orden 1
t1 = tf.constant([1, 3, 4])
print("Vector: \n", t1, "\n")

#Matriz = tensor de orden 2 x 3
t23 = tf.constant([[1, 2, 3],[4, 5, 6]])
print("Matriz: \n", t23, "\n")

#Arreglo = tensor de orden 2x35
t235 = tf.constant([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],
                    [[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]]])
print("Arreglo: \n", t235, "\n")

Escalar:
 tf.Tensor(4, shape=(), dtype=int32) 

Vector: 
 tf.Tensor([1 3 4], shape=(3,), dtype=int32) 

Matriz: 
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) 

Arreglo: 
 tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]], shape=(2, 3, 5), dtype=int32) 



#### Paso 4. Operaciones algebraicas con tensores

In [32]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])

print("a: \n",a,"\n")
print("b: \n",b,"\n")
print("Mayor valor en a:\n", tf.reduce_max(a))
print("Mayor indice en b:\n", tf.argmax(b))
print("a+b: suma de digitos en la misma posición \n",tf.add(a,b),"\n")
print("a*b: multiplcación de digitos en la misma posición \n", tf.multiply(a,b),"\n")
print("a @ b: multiplicación de las dos matrices \n",tf.matmul(a,b),"\n")

a: 
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

b: 
 tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32) 

Mayor valor en a:
 tf.Tensor(4, shape=(), dtype=int32)
Mayor indice en b:
 tf.Tensor([1 1], shape=(2,), dtype=int64)
a+b: suma de digitos en la misma posición 
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

a*b: multiplcación de digitos en la misma posición 
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 

a @ b: multiplicación de las dos matrices 
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



#### Paso 5. Pasar un tensor a un arreglo, ubicar una posición ó una rebanada específica

##### 5.1 - Tensores con un solo eje

In [36]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


In [37]:
print("Primer número:", rank_1_tensor[0].numpy())
print("Quinto número:", rank_1_tensor[4].numpy())
print("Ultimo:", rank_1_tensor[-1].numpy())

Primer número: 0
Quinto número: 3
Ultimo: 34


In [40]:
print("Todo:", rank_1_tensor[:].numpy())
print("Antes del 4to:", rank_1_tensor[:4].numpy())
print("Del 4to en adelante:", rank_1_tensor[4:].numpy())
print("Entre el 2do y el 7mo:", rank_1_tensor[2:7].numpy())
print("Saltando de a 3:", rank_1_tensor[::3].numpy())
print("En el orden inverso:", rank_1_tensor[::-1].numpy())

Todo: [ 0  1  1  2  3  5  8 13 21 34]
Antes del 4to: [0 1 1 2]
Del 4to en adelante: [ 3  5  8 13 21 34]
Entre el 2do y el 7mo: [1 2 3 5 8]
Saltando de a 2: [ 0  2  8 34]
En el orden inverso: [34 21 13  8  5  3  2  1  1  0]


##### 5.2 Tensores con mas de un eje

In [42]:
rank_2_tensor = tf.constant([[1,2],[3,4], [5,6]])
print(rank_2_tensor.numpy())

[[1 2]
 [3 4]
 [5 6]]


In [47]:
print("Mostrando el número en la posición 1, 1 :", rank_2_tensor[1, 1].numpy())
print("Mostrando la segunda fila:", rank_2_tensor[1, :].numpy())
print("Mostrando la segunda columna:", rank_2_tensor[:, 1].numpy())
print("Última fila:", rank_2_tensor[-1, :].numpy())
print("Primer número en la última columna:", rank_2_tensor[0, -1].numpy())
print("Saltando la primera fila:\n ", rank_2_tensor[1:, :].numpy())

Mostrando el número en la posición 1, 1 : 4
Mostrando la segunda fila: [3 4]
Mostrando la segunda columna: [2 4 6]
Última fila: [5 6]
Primer número en la última columna: 2
Saltando la primera fila:
  [[3 4]
 [5 6]]


#### Paso 6. Manipulación de su forma (shape)

La forma de un tensor nos dice la longitud de cada uno de los ejes del tensor. En los ejemplos anteriores podemos confirmar esto. Es posible crear un tensor con varios ejes lleno de ceros, lo que nos permite ver sus propiedades:

In [35]:
#Tenso de 4 ejes llenos de 0
rank_4_tensor = tf.zeros([3, 2, 4, 5])
print("Tipo de los elementos:", rank_4_tensor.dtype)
print("Numero de ejes:", rank_4_tensor.ndim)
print("Forma del tensor:", rank_4_tensor.shape)
print("Elementos en el axis 0:", rank_4_tensor.shape[0])
print("Elementos en el ultimo eje del tensor:", rank_4_tensor.shape[-1])
print("Numero total de elementos en el tensor (3*2*4*5): ", tf.size(rank_4_tensor).numpy())
print("Tensor:\n", rank_4_tensor)

Tipo de los elementos: <dtype: 'float32'>
Numero de ejes: 4
Forma del tensor: (3, 2, 4, 5)
Elementos en el axis 0: 3
Elementos en el ultimo eje del tensor: 5
Numero total de elementos en el tensor (3*2*4*5):  120
Tensor:
 tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(3, 2, 4, 5), dtype=float32)



Ahora podemos cambiar su forma (Reshape) y evitar duplicar datos

In [54]:
reshaped = tf.reshape(rank_4_tensor, [1, 120])
print(rank_4_tensor.shape, "dónde 3 x 2 x 4 x 5 = 120")
print(reshaped.shape, "los mismos 120 pero en una sola fila")

(3, 2, 4, 5) dónde 3 x 2 x 4 x 5 = 120
(1, 120) los mismos 120 pero en una sola fila


#### Paso 7. Aplanar un tensor

Al aplanar dar la forma que requieres, pero debes respetar el orden de los ejes, porque de lo contrario mezclas información, lo cual no es correcto. 

In [58]:
print("Con -1 le pedimos que los ajuste a lo que mejor funcione, en este caso \n \n", tf.reshape(rank_4_tensor, [-1]))

Con -1 le pedimos que los ajuste a lo que mejor funcione, en este caso 
 
 tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(120,), dtype=float32)


#### Paso 8. Transmitir (Broadcasting) 

Se requiere cuando trabajas con tensores de diferentes formas, uno mas pequeño que el otro, y requieres un calculo entre ellos.

In [67]:
rank_1_tensor = tf.constant([1, 2, 3])
rank_0_tensor = tf.constant(2)

print("Multiplicar el tensor de 1 eje por 2", tf.multiply(rank_1_tensor, 2))
print("Lo mismo pero entre tensores de tamaño distinto, estos es broadcasting:", rank_1_tensor * rank_0_tensor)

Multiplicar el tensor de 1 eje por 2 tf.Tensor([2 4 6], shape=(3,), dtype=int32)
Lo mismo pero entre tensores de tamaño distinto, estos es broadcasting: tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [68]:
reshape_rank_1_tensor = tf.reshape(rank_1_tensor,[3,1])
rank_1_tensor_2 = tf.range(1, 5)
print(reshape_rank_1_tensor, "\n")
print(rank_1_tensor_2, "\n")
print("Esto es broadcasting, porque el segundo solo tiene un eje y el primero 3: \n", tf.multiply(reshape_rank_1_tensor, rank_1_tensor_2))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

Esto es broadcasting, porque el segundo solo tiene un eje y el primero 3: 
 tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


#### Paso 9. Tensores tipo irregulares (ragged)

Hasta aqui los tensores tenian formas completas, ahora veremos que no siempre es el caso.

In [70]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)
print(ragged_tensor.shape)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>
(4, None)


#### Paso 10. Tensor tipo cadena (string)

Los tensores no solo manejan números, también permite manejar cadenas de caracteres, estos tensores no marcan la longitud de los tensores.

In [75]:
scalar_string_tensor = tf.constant("Perro de color capuchino")
print(scalar_string_tensor, "\n")

tensor_of_strings = tf.constant(["Perro de color capuchino",
                                 "Gato de color amarillo",
                                 "Paloma de color blanco"])

print(tensor_of_strings)

tf.Tensor(b'Perro de color capuchino', shape=(), dtype=string) 

tf.Tensor(
[b'Perro de color capuchino' b'Gato de color amarillo'
 b'Paloma de color blanco'], shape=(3,), dtype=string)


#### Paso 11. Tesores tipo dispersos (sparse)

No siempre tus datos van a estar completos y pueden estar dispersos, por lo que es posible manejar tensores completos, pero con los valores espaciados, para sto debes manejar indices, que delimitan donde van los números.

In [79]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
print("Tensor de tamaño 3 x 4 con valores en la posición 0,0 y en la 1,2 \n")
print(tf.sparse.to_dense(sparse_tensor))

Tensor de tamaño 3 x 4 con valores en la posición 0,0 y en la 1,2 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)



Esto es lo que he aprendido de tensores, muy bonitos.

